#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Merge this workspace's auto-mode classifier rules (automode.json at the repo
# root, consumer-owned) into ~/.claude/settings.json — the only file the
# classifier reads them from, and only at session start.
#
# Where to run it:
#   - Claude Code on the web: from the environment's setup script, so the
#     rules exist before the session starts. If the setup script runs before
#     the repo is cloned, paste the output of `install.sh --inline` instead —
#     a self-contained block that carries the rules with it.
#   - A local machine: once, by hand. An agent cannot do this for you: in auto
#     mode the classifier denies the write as self-modification, and a change
#     made mid-session is not honoured anyway (measured 2026-09-20).
#
# Idempotent, merge-safe (only the autoMode key is replaced), exits 0 on any
# failure so it can never block a session from starting. The SessionStart
# hook agent-tools/hooks/automode-check.sh reports whether what is installed
# matches the repo.
# ---------------------------------------------------------------------------
set -uo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
CANON="${AUTOMODE_RULES:-$ROOT/automode.json}"
TARGET="$HOME/.claude/settings.json"

[ -f "$CANON" ] || { echo "automode: no $CANON — nothing to install"; exit 0; }

if [ "${1:-}" = "--inline" ]; then
  cat <<SNIP
# --- auto-mode classifier rules (generated by agent-tools/automode/install.sh --inline) ---
python3 - <<'PY' || true
import json, os, pathlib
rules = json.loads(r'''$(cat "$CANON")''')["autoMode"]
p = pathlib.Path(os.path.expanduser("~/.claude/settings.json")); p.parent.mkdir(parents=True, exist_ok=True)
try: cur = json.loads(p.read_text())
except Exception: cur = {}
cur["autoMode"] = rules
p.write_text(json.dumps(cur, indent=2) + "\n")
print("automode: rules installed")
PY
# --- end auto-mode rules ---
SNIP
  exit 0
fi

python3 - "$CANON" "$TARGET" <<'PY' || echo "automode: install failed (non-fatal)"
import json, pathlib, sys
canon, target = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
rules = json.loads(canon.read_text())["autoMode"]
target.parent.mkdir(parents=True, exist_ok=True)
try: cur = json.loads(target.read_text())
except Exception: cur = {}
if cur.get("autoMode") == rules:
    print(f"automode: {target} already matches {canon.name}"); raise SystemExit
cur["autoMode"] = rules
target.write_text(json.dumps(cur, indent=2) + "\n")
print(f"automode: installed {canon.name} into {target}")
PY
exit 0
